### ISSUE TITLE
[2 May] Experiment: train probe per prompt

### ISSUE THREAD

**Issue by derpyplops** [Cadenza-Labs/elk#9]
See https://www.lesswrong.com/posts/bFwigCDMC5ishLz7X/rfc-possible-ways-to-expand-on-discovering-latent-knowledge#Additional_ideas_that_came_up_while_writing_this_post_
Point 2

*note: Imported from old project*

**Comment by lauritowal** [comment]
@derpyplops @KayKozaronek Could you add an estimated deadline for this to the title?
